# Config file for MW

modules:
  - gsl/2.5
  - perl/5.38.0
  - bcftools/1.20
  - plink/1.9.0
  - admixture/1.3.0
  - king/2.3.1
  - openblas/0.3.24
  - eigensoft/8.0.0
  - vcftools/0.1.17
  - python/2.7.17
  - angsd/0.940
  - samtools/1.21

# === Input files ===
vcf: "/projects/psg/data/Shyam_sharing/bcf/phased.all.info08.name.excludesamples.bcf"

# Sample lists
wolves_list: "data/wolvesandcanids.txt"
eu_wolves_list: "data/europeanwolvesandcanids.txt"
wolves_only_list: "data/wolvesonly.txt"
eu_wolves_only_list: "data/europeanwolvesonly.txt"
meta: "data/allcanids_metadata_ancestrygroups_new_related_edited.txt"
ancient_bams: "data/ancientwolves_bams.txt"
ref_genome: "/projects/psg/people/pkb156/MW/data/canFam31.fasta"


#lists
convertfancient: "scripts/convertf_ancient.par"
convertfmodern: "scripts/convertf_modern.par"
mergeit: "scripts/mergeit_ancient_modern.par"
haplonetfiles: "scripts/haplonet.filelist"

# K range for admixture analysis
K_range: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

#chromosomes
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]

#replicates and migrations for orientagraph
migrations: [0, 1, 2, 3, 4, 5]
replicates: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Locations for pi diversity
pi_locations: ["Slovakia", "Ukraine", "Poland", "Finland",
    "Russia", "Sweden", "Lithuania", "Latvia",
    "Denmark", "Czech-Republic", "Germany", "Austria",
    "Scandinavia", "Romania", "Bulgaria", "Croatia",
    "Greece", "Bosnia-and-Herzegovina", "China", "Korea",
    "Kazakhstan", "Mongolia", "Estonia", "Italy", "Norway",
    "Spain", "Turkey", "Israel", "Portugal",
    "Belarus", "India", "Iran", "Saudi", "Syria"]